name: test

on:
  push:
    branches: [ main ]
    paths:
      - 'test/**'

  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:

  build:

   runs-on: ubuntu-latest

   steps:

     - uses: actions/checkout@v2

     - name: Compile
       run: make -C test
